version: "3.7"

services:
  postgres:
    image: postgres:12

    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  migrations:
    depends_on:
      - postgres

    build:
      context: .
      target: devserver
    image: hanabi-dev

    entrypoint: ["hanabi/manage.py", "migrate"]
    environment:
      DB_HOST: postgres
      DB_PASSWORD: password

  server:
    depends_on:
      - migrations

    build:
      context: .
      target: devserver
    image: hanabi-dev

    environment:
      ALLOWED_HOSTS: 0.0.0.0,127.0.0.1,localhost
      DB_HOST: postgres
      DB_PASSWORD: password
    ports:
      # Devserver runs on port 8000
      - 8000:8000
    volumes:
      - ./:/opt/hanabi
