version: "3.7"

services:
  postgres:
    image: postgres:12
  ports:
    - 5432:5432
  volumes:
    - "/tmp/hanabi-data:/var/lib/postgresql/data"

  server:
    build:
      context: .
      target: devserver
    image: hanabi-dev

    ports:
      # Flask defaults to running on port 5000
      - 5000:5000
    volumes:
    - ./:/opt/hanabi
