version: "3.7"

services:
  server:
    build:
      context: .
      target: devserver
    image: hanabi-dev

    ports:
      # Flask defaults to running on port 5000
      - 5000:5000
    volumes:
    - ./:/opt/hanabi
