# Generated by Django 3.0.4 on 2020-03-29 20:40

from django.db import migrations, models
import game.models.lobbies
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lobby",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=game.models.lobbies.generate_lobby_code,
                        max_length=5,
                        unique=True,
                        verbose_name="access code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at"
                    ),
                ),
            ],
            options={
                "verbose_name": "lobby",
                "verbose_name_plural": "lobbies",
                "ordering": ("created_at",),
            },
        ),
    ]
