# Generated by Django 3.0.4 on 2020-03-29 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LobbyMember",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_owner",
                    models.BooleanField(
                        default=False,
                        help_text="A boolean indicating if the member is the owner of the lobby. The lobby owner has additional permissions such as being able to delete the lobby.",
                        verbose_name="is owner",
                    ),
                ),
                ("name", models.SlugField(verbose_name="name")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at"
                    ),
                ),
                (
                    "lobby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        related_query_name="member",
                        to="game.Lobby",
                        verbose_name="lobby",
                    ),
                ),
            ],
            options={
                "verbose_name": "lobby member",
                "verbose_name_plural": "lobby members",
                "ordering": ("created_at",),
            },
        ),
    ]
