# Generated by Django 3.0.4 on 2020-03-29 22:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "color",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Blue"),
                            (2, "Green"),
                            (3, "Rainbow"),
                            (4, "Red"),
                            (5, "White"),
                            (6, "Yellow"),
                        ],
                        verbose_name="color",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "deck_order",
                    models.PositiveSmallIntegerField(
                        verbose_name="deck order"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="number"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated at"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        related_query_name="card",
                        to="game.Game",
                        verbose_name="game",
                    ),
                ),
            ],
            options={
                "verbose_name": "card",
                "verbose_name_plural": "cards",
                "ordering": ("game", "deck_order"),
                "unique_together": {("deck_order", "game")},
            },
        ),
    ]
