# Generated by Django 3.0.4 on 2020-03-29 22:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "action_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Discard"),
                            (2, "Draw"),
                            (3, "Hint"),
                            (4, "Order Hand"),
                            (5, "Play"),
                        ],
                        verbose_name="action type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        related_query_name="action",
                        to="game.Game",
                        verbose_name="game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        related_query_name="action",
                        to="game.Player",
                        verbose_name="player",
                    ),
                ),
            ],
            options={
                "verbose_name": "action",
                "verbose_name_plural": "actions",
                "ordering": ("game", "created_at"),
                "unique_together": {("created_at", "game")},
            },
        ),
    ]
