# Generated by Django 3.0.4 on 2020-03-30 00:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_drawaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="HintAction",
            fields=[
                (
                    "color",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Blue"),
                            (2, "Green"),
                            (3, "Rainbow"),
                            (4, "Red"),
                            (5, "White"),
                            (6, "Yellow"),
                        ],
                        null=True,
                        verbose_name="color",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name="number"
                    ),
                ),
                (
                    "action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hint_action",
                        to="game.Action",
                        verbose_name="action",
                    ),
                ),
            ],
            options={
                "verbose_name": "hint action",
                "verbose_name_plural": "hint actions",
            },
        ),
        migrations.AddConstraint(
            model_name="hintaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ("color__isnull", False), ("number__isnull", True)
                        ),
                        models.Q(
                            ("color__isnull", True), ("number__isnull", False)
                        ),
                        _connector="OR",
                    )
                ),
                name="cix_color_xor_number",
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="hintaction", order_with_respect_to="action",
        ),
    ]
