# Generated by Django 3.0.4 on 2020-03-30 00:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_hintaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="HintCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hint_cards",
                        related_query_name="hint_card",
                        to="game.Card",
                        verbose_name="card",
                    ),
                ),
                (
                    "hint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        related_query_name="card",
                        to="game.HintAction",
                        verbose_name="hint",
                    ),
                ),
            ],
            options={
                "verbose_name": "hint card",
                "verbose_name_plural": "hint cards",
                "unique_together": {("card", "hint")},
            },
        ),
    ]
