# Generated by Django 3.0.4 on 2020-03-30 01:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_hintcard"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "was_successful",
                    models.BooleanField(verbose_name="was successful"),
                ),
                (
                    "action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_action",
                        to="game.Action",
                        verbose_name="action",
                    ),
                ),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_action",
                        to="game.Card",
                        verbose_name="card",
                    ),
                ),
            ],
            options={
                "verbose_name": "play action",
                "verbose_name_plural": "play actions",
                "order_with_respect_to": "action",
            },
        ),
    ]
