# Generated by Django 3.0.4 on 2020-03-30 02:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_playaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerHand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hands",
                        related_query_name="hand",
                        to="game.Player",
                        verbose_name="player",
                    ),
                ),
                (
                    "source_action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resulting_hand",
                        to="game.Action",
                        verbose_name="source action",
                    ),
                ),
            ],
            options={
                "verbose_name": "player hand",
                "verbose_name_plural": "player hands",
            },
        ),
        migrations.CreateModel(
            name="PlayerHandCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="game.Card",
                        verbose_name="card",
                    ),
                ),
                (
                    "hand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        related_query_name="card",
                        to="game.PlayerHand",
                        verbose_name="hand",
                    ),
                ),
            ],
            options={
                "verbose_name": "player hand card",
                "verbose_name_plural": "player hand cards",
                "order_with_respect_to": "hand",
            },
        ),
    ]
