# Generated by Django 3.0.4 on 2020-04-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_player_order_unique"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lobbymember", unique_together={("lobby", "name")},
        ),
    ]
