# Generated by Django 3.0.4 on 2020-04-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_unique_lobbymember_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawaction",
            name="card",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draw_action",
                to="game.Card",
                verbose_name="card",
            ),
        ),
    ]
