# Generated by Django 3.0.4 on 2020-04-03 20:57

from django.db import migrations, models


def populate_color_names(apps, _):
    Card = apps.get_model("game", "Card")
    HintAction = apps.get_model("game", "HintAction")

    for Model in [Card, HintAction]:
        Model.objects.filter(color=1).update(color_name="BLUE")
        Model.objects.filter(color=2).update(color_name="GREEN")
        Model.objects.filter(color=3).update(color_name="RAINBOW")
        Model.objects.filter(color=4).update(color_name="RED")
        Model.objects.filter(color=5).update(color_name="WHITE")
        Model.objects.filter(color=6).update(color_name="YELLOW")


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_drawaction_card_onetoone"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="color_name",
            field=models.CharField(
                choices=[
                    ("BLUE", "Blue"),
                    ("GREEN", "Green"),
                    ("RAINBOW", "Rainbow"),
                    ("RED", "Red"),
                    ("WHITE", "White"),
                    ("YELLOW", "Yellow"),
                ],
                max_length=7,
                null=True,
                verbose_name="color",
            ),
        ),
        migrations.AddField(
            model_name="hintaction",
            name="color_name",
            field=models.CharField(
                choices=[
                    ("BLUE", "Blue"),
                    ("GREEN", "Green"),
                    ("RAINBOW", "Rainbow"),
                    ("RED", "Red"),
                    ("WHITE", "White"),
                    ("YELLOW", "Yellow"),
                ],
                max_length=7,
                null=True,
                verbose_name="color",
            ),
        ),
        # Populate the new color name fields
        migrations.RunPython(
            code=populate_color_names, reverse_code=migrations.RunPython.noop
        ),
        # Remove ability for fields to be null
        migrations.AlterField(
            model_name="card",
            name="color_name",
            field=models.CharField(
                choices=[
                    ("BLUE", "Blue"),
                    ("GREEN", "Green"),
                    ("RAINBOW", "Rainbow"),
                    ("RED", "Red"),
                    ("WHITE", "White"),
                    ("YELLOW", "Yellow"),
                ],
                max_length=7,
                verbose_name="color",
            ),
        ),
        migrations.AlterField(
            model_name="hintaction",
            name="color_name",
            field=models.CharField(
                choices=[
                    ("BLUE", "Blue"),
                    ("GREEN", "Green"),
                    ("RAINBOW", "Rainbow"),
                    ("RED", "Red"),
                    ("WHITE", "White"),
                    ("YELLOW", "Yellow"),
                ],
                max_length=7,
                verbose_name="color",
            ),
        ),
        # Remove the old numeric fields
        migrations.RemoveConstraint(
            model_name="hintaction", name="cix_color_xor_number"
        ),
        migrations.RemoveField(model_name="card", name="color",),
        migrations.RemoveField(model_name="hintaction", name="color",),
        # Rename the new string fields to match the old numeric ones
        migrations.RenameField(
            model_name="card", old_name="color_name", new_name="color",
        ),
        migrations.RenameField(
            model_name="hintaction", old_name="color_name", new_name="color",
        ),
        migrations.AddConstraint(
            model_name="hintaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ("color__isnull", False), ("number__isnull", True)
                        ),
                        models.Q(
                            ("color__isnull", True), ("number__isnull", False)
                        ),
                        _connector="OR",
                    )
                ),
                name="cix_color_xor_number",
            ),
        ),
    ]
