# Generated by Django 3.0.4 on 2020-04-03 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0016_card_color_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discardaction",
            name="card",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discard_action",
                to="game.Card",
                verbose_name="card",
            ),
        ),
    ]
