# Generated by Django 3.0.4 on 2020-04-04 15:28

from django.db import migrations, models
import django.db.models.deletion


def drop_null_hint_action_players(apps, schema_editor):
    HintAction = apps.get_model("game", "HintAction")
    HintAction.objects.filter(target_player__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_discardaction_onetoone"),
    ]

    operations = [
        migrations.AddField(
            model_name="hintaction",
            name="target_player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hints",
                related_query_name="hint",
                to="game.Player",
                verbose_name="target player",
            ),
        ),
        # Drop any rows that would cause an error due to enforcing the
        # non-null constraint.
        migrations.RunPython(
            code=drop_null_hint_action_players,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="hintaction",
            name="target_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hints",
                related_query_name="hint",
                to="game.Player",
                verbose_name="target player",
            ),
        ),
    ]
