# Generated by Django 3.0.4 on 2020-04-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0018_hintaction_target_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hintaction",
            name="color",
            field=models.CharField(
                choices=[
                    ("BLUE", "Blue"),
                    ("GREEN", "Green"),
                    ("RAINBOW", "Rainbow"),
                    ("RED", "Red"),
                    ("WHITE", "White"),
                    ("YELLOW", "Yellow"),
                ],
                max_length=7,
                null=True,
                verbose_name="color",
            ),
        ),
    ]
