"""Create hint action table

Revision ID: 6d3955140753
Revises: c19bda1d3671
Create Date: 2020-03-29 01:15:59.556596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6d3955140753"
down_revision = "c19bda1d3671"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "hint_action",
        sa.Column("action_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("card_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "color",
            postgresql.ENUM(
                "BLUE",
                "GREEN",
                "RED",
                "WHITE",
                "YELLOW",
                # Enum already created for `card` table.
                create_type=False,
                name="cardcolor",
            ),
            nullable=True,
        ),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=True),
        sa.Column(
            "target_player_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.CheckConstraint(
            "(color IS NULL) != (number IS NULL)", name="check_color_or_number"
        ),
        sa.ForeignKeyConstraint(["action_id"], ["action.id"],),
        sa.ForeignKeyConstraint(["card_id"], ["card.id"],),
        sa.ForeignKeyConstraint(["target_player_id"], ["player.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table("hint_action")
    # ### end Alembic commands ###
