"""Create play action table

Revision ID: 769a02209a28
Revises: 24be25ba2ebf
Create Date: 2020-03-29 00:26:42.958012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "769a02209a28"
down_revision = "24be25ba2ebf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "play_action",
        sa.Column("action_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("card_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("was_successful", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["action_id"], ["action.id"],),
        sa.ForeignKeyConstraint(["card_id"], ["card.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table("play_action")
    # ### end Alembic commands ###
