"""Create discard action table

Revision ID: c19bda1d3671
Revises: 769a02209a28
Create Date: 2020-03-29 00:40:34.021026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c19bda1d3671"
down_revision = "769a02209a28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "discard_action",
        sa.Column("action_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("card_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["action_id"], ["action.id"],),
        sa.ForeignKeyConstraint(["card_id"], ["card.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table("discard_action")
    # ### end Alembic commands ###
