"""Create player table

Revision ID: d0f8e834cd9f
Revises: ec4ae17fb997
Create Date: 2020-03-28 14:52:04.265854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d0f8e834cd9f"
down_revision = "ec4ae17fb997"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "player",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("lobby_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["lobby_id"], ["lobby.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lobby_id", "name", name="uix_lobby_players"),
        sa.UniqueConstraint(
            "lobby_id", "order", name="uix_lobby_player_order"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table("player")
    # ### end Alembic commands ###
