"""Create player hand action table

Revision ID: e2f330609bff
Revises: fd45a3ed0be0
Create Date: 2020-03-29 10:58:31.311581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e2f330609bff"
down_revision = "fd45a3ed0be0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "set_player_hand_action",
        sa.Column("action_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["action_id"], ["action.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "set_player_hand_action_card",
        sa.Column("card_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("order", sa.SmallInteger(), nullable=False),
        sa.Column(
            "set_hand_action_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.ForeignKeyConstraint(["card_id"], ["card.id"],),
        sa.ForeignKeyConstraint(
            ["set_hand_action_id"], ["set_player_hand_action.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order", "set_hand_action_id", name="uix_player_hand_order"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table("set_player_hand_action_card")
    op.drop_table("set_player_hand_action")
    # ### end Alembic commands ###
