"""Create lobby table

Revision ID: ec4ae17fb997
Revises:
Create Date: 2020-03-27 23:19:55.351185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ec4ae17fb997"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lobby",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("code", sa.VARCHAR(length=5), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lobby")
    # ### end Alembic commands ###
