"""Create game table

Revision ID: fbe03d87119c
Revises: d0f8e834cd9f
Create Date: 2020-03-28 18:03:27.050768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fbe03d87119c"
down_revision = "d0f8e834cd9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "game",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_in_progress", sa.Boolean(), nullable=False),
        sa.Column("lobby_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["lobby_id"], ["lobby.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table("game")
    # ### end Alembic commands ###
