name: Review Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Run Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Check style with black
        run: black --check .

      - name: Test with pytest
        run: pytest hanabi/
